name: 'OSSR-record-setup'
description: 'Prepare a directory before upload to the OSSR'
inputs:
  output_dir:  # id of input
    description: 'Output directory'
    required: true
    default: 'build'
  repository_url:
    description: Repository URL - can be given as $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
    required: true
runs:
  using: "composite"
  steps:
    - name: prepare directory to zenodo
    - run: ${{ github.action_path }}/zenodo_prepare_upload.sh ${{ inputs.output_dir }} ${{ inputs.repository_url }}
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
