name: 'OSSR-new-record'
description: 'Upload new record to the OSSR'
inputs:
  repository_url:
    description: Repository URL - can be given as $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
    required: true
  token:
    description: Zenodo token (or sandbox.zenodo token if sandbox is True)
    required: true
  sandbox:
    description: Using sandbox if True
    required: false
    default: False

runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/zenodo_prepare_upload.sh BUILD_OSSR ${{ inputs.repository_url }} 
        echo "preparation over"
      shell: bash
    - name: upload to OSSR
      uses: docker://gitlab-registry.in2p3.fr/escape2020/wp3/zenodoci:v1.2
      with:
        entrypoint: upload_new_deposit
        args:  --token ${{ inputs.token }} --sandbox ${{ inputs.sandbox }} --input-dir BUILD_OSSR

